### ISSUE TITLE
Long command name

### ISSUE THREAD

**Issue by jake-walker** [silvertern/cli#5]
On Windows, the program name seems to always be the absolute path to the executable like so:

![image](https://user-images.githubusercontent.com/10981005/116001019-67f56d80-a5ea-11eb-9385-74cbbe6abb60.png)

Perhaps this is intentional, but it makes the help message unnecessarily long. Could the program name be just the filename of the command rather than the path? Or perhaps could it be manually overridden? Perhaps like this:

```go
app := cli.New("myapp", "here is the description...")
```

**Comment by osklyar** [comment]
Would you mind suggesting a patch? It should be pretty trivial to drop both the path and the extension.

**Comment by DarkCeptor44** [comment]
Well this is awkward but it's not fixed... and I don't know why:

![image](https://github.com/teris-io/cli/assets/16278483/376bae1d-0b4e-4c1a-8313-9d6987ea39f0)
